Host: http://localhost:8000

POST /liker/users/singup/
{
    "email": "barbara_streisand@protonmail.com",
    "username": "artfulsdf_restore",
    "password": "liker"
}


#expected to fail
Authorization: Basic a2FkbWluMzQyMzQyNDpsaWtlcg==

POST /liker/users/singup/
{
    "email": "barbara_streisand@protonmail.com",
    "username": "kadmin34424",
    "password": "liker"
}


TEMPLATE access_token
Authorization: Bearer ${json["access"]}

# the login view
# initial username/password auth
# Authorization: Basic a2FkbWluX3BhdGNod29ya19vcnQ6bGlrZXI=
# Authorization: Brasic YXJ0ZnVsX3Jlc3RvcmU6bGlrZXI=

# Authorization: Basic YXJ0ZnVsX3Jlc3RvcmU6bGlrZXI=
Authorization: Basic YWRtaW46YWRtaW4xOTkw
# Authorization: Basic YXJ0ZnVsc2RmX3Jlc3RvcmU6bGlrZXI=

POST /liker/users/token/ | access_token


########################################

# generate token with prev token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NDkxMDgxLCJqdGkiOiJjODhiMjhhZGU1ZmQ0ZWYyYmY1MjU4ZjBkZjRjNGRkMCIsInVzZXJfaWQiOjExfQ.Jg_nAl9XR4Brxzqp_nLWxPOT-ZLHLsoc_YuwlbALRgM

POST /liker/users/token/


Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NjUzOTA4LCJqdGkiOiI4YThjMmFmYWExYjE0N2Y4OWQ1MmZmMzE0ZWIwZThiNiIsInVzZXJfaWQiOjZ9.hZybTvEi8G0kdqnttWLEoG-s094wfUx6nJTPQ-2waWk
Content-Type: application/json

POST /liker/posts/
{
        "title": "once upon a time",
        "body": "mind of beautiful kind happended"
}


Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NzE3ODg5LCJqdGkiOiIwMmY4YTc5OTMzZmQ0MzkyYmI4NmQxMjhlYjg0MThlNCIsInVzZXJfaWQiOjV9.Cwr4u3xCyIFwE6tAPyrXXDdaUpFau0pp1LnXq_pbz50

GET /liker/posts/


Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NzIyMTcwLCJqdGkiOiIyNDY0ZmYwZDFlYTM0NGZmOWVhNjZlYjk5MzA3Yzg3ZiIsInVzZXJfaWQiOjV9.aHbC6D_6nTnUqd54dF50EkWrzY1B6H4UHJv7Mx2zEFQ

POST /liker/posts/700/like/


Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NTY3Mzc3LCJqdGkiOiIwOGJjNDliMzRkMmU0MjUzYWU5NGRkYWI5YTlhMzUwNSIsInVzZXJfaWQiOjE2fQ.WKe8MGib9cs9-0BfbYPcfd-NZ5XHHAj58qcjdu_9j2I

POST /liker/posts/9/unlike/


Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NTgyMzY0LCJqdGkiOiI3MDIxOWM5YTU4YjM0MjU3YmY5ZDMzMmYxOThlNTBhZCIsInVzZXJfaWQiOjE3fQ.Nu9YLdWzIqfZtDCx7Ni7IsuWniONXZcYcKiMaBuGYN0

GET /liker/actions/


Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NjMzMTA5LCJqdGkiOiJlZTgwMzkzMjMzMGU0ZWRhODU2NTUxMTU0OTExODdjOSIsInVzZXJfaWQiOjE3fQ.AM-IfXmbQ6FMhuV-E2un-CE2mIoFOjgGpKwO4D7taF0

GET /liker/user/17/last_actions

Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg3NzIzMTQwLCJqdGkiOiI3NDhiYzNiNWU3NGM0MGE2OGU4ZGRhNDE1NTdlNzRiYSIsInVzZXJfaWQiOjEwMn0.7byRIN6Rk9Q---YEx_WyR4PkCaeEZQNWMRl23ap1CaY

GET /liker/api/analytics/?date_from=2020-04-21&date_to=2020-04-24

