# Generated by Django 3.0.5 on 2020-04-21 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_liker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_liker.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='users_like',
            field=models.ManyToManyField(related_name='posts_liked', through='post_liker.LikingActivity', to=settings.AUTH_USER_MODEL),
        ),
    ]
